spring:

  # PostgreSQL
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
      kid: ${OAUTH2_KID}
      issuer: ${OAUTH2_ISSUER_URI}
    key:
      public:
        path: /app/public.pem
      private:
        path: /app/private.pem

  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Email SMTP
  mail:
    enable: true
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    team: ${MAIL_TEAM}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
