spring:

  # local PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
      kid: auth-base-kid
      issuer: http://localhost:8080
    key:
      public:
        path: /home/rolemberg/Documentos/Programming/projects/java/auth-base/app/public.pem
      private:
        path: /home/rolemberg/Documentos/Programming/projects/java/auth-base/app/private.pem

  # JPA
  jpa:
    #hibernate:
    #  ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Email SMTP
  mail:
    enable: true
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    team: ${MAIL_TEAM}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
