name: Build e Push no ECR

on:
  push:
    branches: [main]

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: auth-base

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Define env
        id: set-env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" = "develop" ]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "environment=" >> $GITHUB_OUTPUT
          fi
          echo "aws_region=sa-east-1" >> $GITHUB_OUTPUT

  test:
    needs: set-env
    uses: ./.github/workflows/test.yml
    secrets: inherit

  terraform-validate:
    needs: [ set-env, test ]
    uses: ./.github/workflows/tf_validate.yml
    secrets: inherit
    with:
      environment: ${{ needs.set-env.outputs.environment }}

  terraform-plan:
    needs: [set-env, terraform-validate]
    uses: ./.github/workflows/tf_plan.yml
    secrets: inherit
    with:
      environment: ${{ needs.set-env.outputs.environment }}

  terraform-apply:
    needs: [ set-env, terraform-validate, terraform-plan ]
    uses: ./.github/workflows/tf_apply.yml
    secrets: inherit
    with:
      environment: ${{ needs.set-env.outputs.environment }}

  build-and-push:
    needs: [ set-env, terraform-apply ]
    uses: ./.github/workflows/deploy_ecr.yml
    secrets: inherit
